# Generated by Django 3.2.5 on 2021-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=65),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
